server:
  port: 5005
spring:
  datasource:
    url: jdbc:mysql://db1:3306/springcloud-java0422?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: UserProvider
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:10086/eureka,http://eureka2:10087/eureka
version: UserProvider02-0.0.1V